// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var HAProxy, Q, data, debug, dnode, handlebars, handlers, print, program, serf, server, start, _;

  _ = require('underscore');

  handlebars = require('handlebars');

  program = require('commander');

  HAProxy = require('haproxy');

  dnode = require('dnode');

  Q = require('q');

  start = require("" + __dirname + "/haproxy").start;

  debug = require("" + __dirname + "/utils").debug;

  serf = require("" + __dirname + "/serf");

  print = debug('main');

  program.version('0.0.0').option('-t --template <.handlebars>', 'HAProxy config template in handlebars', require).parse(process.argv);

  if (program.template == null) {
    program.template = require("" + __dirname + "/../example/haproxy.config");
  }

  if (!_.isFunction(program.template)) {
    throw new Error('invalid template');
  }

  handlers = {
    print: print
  };

  server = dnode(handlers).listen("" + __dirname + "/../synapse.sock");

  data = {
    roles: [
      {
        "role": "apache",
        "server": [
          {
            "name": "server1",
            "address": "127.0.0.1:1234"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1235"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1236"
          }
        ]
      }, {
        "role": "cometd",
        "server": [
          {
            "name": "server1",
            "address": "127.0.0.1:1234"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1235"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1236"
          }
        ]
      }, {
        "role": "ngix",
        "server": [
          {
            "name": "server1",
            "address": "127.0.0.1:1234"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1235"
          }, {
            "name": "server1",
            "address": "127.0.0.1:1236"
          }
        ]
      }
    ]
  };

}).call(this);
